In [1]:
import numpy as np
a=np.array([1,2,3]);
b=np.array([[1,2,3],[4,5,6]])
c=np.array([['a','b','c'],[1,2,3],['@','#','$']])
print("1d-array ",a)
print("2d_array",b)
print('3rd array',c)
print("a*b",a*b)

1d-array  [1 2 3]
2d_array [[1 2 3]
 [4 5 6]]
3rd array [['a' 'b' 'c']
 ['1' '2' '3']
 ['@' '#' '$']]
a*b [[ 1  4  9]
 [ 4 10 18]]


In [15]:
# Using NumPy's mathematical functions
arr = np.array([1, 2, 3, 4, 5])
print("Square root:", np.sqrt(arr))
print("Sine:", np.sin(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))


Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Mean: 3.0
Sum: 15


In [8]:
# Random array
random_arr = np.random.rand(2, 2)
random_arr=random_arr*10
print("2x2 Array with random values:\n", random_arr)


2x2 Array with random values:
 [[2.57951045 8.33673757]
 [1.50374076 3.74577801]]


In [10]:
zero=np.zeros((3,2))
print(zero)
one=np.ones((2,2))
print(one)
idm=np.eye((4))
print(idm)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
